name: Update Wiki sidebar menu



on:
  gollum
  workflow_dispatch:

jobs:
  genmenu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install github-wiki-sidebar
        run: npm install github-wiki-sidebar -g

      - name: Generate the sidebar
        run: github-wiki-sidebar --silent
