name: Update Wiki sidebar menu

on:
  gollum

jobs:
  genmenu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install github-wiki-sidebar
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://github.com/ppfn/hib_doc.wiki.git
          cd hib_doc.wiki
          npm install github-wiki-sidebar -g
          github-wiki-sidebar --silent --git-push
